"""Owner-provided and code-checked EN/ES copy for the public Petfy site."""

PAGES = {
    "privacy": {
        "file": "privacy.html",
        "title": {"es": "Privacidad en Petfy", "en": "Privacy at Petfy"},
        "summary": {
            "es": "Qué información usamos, para qué sirve y cómo puedes decidir sobre tus datos.",
            "en": "What information we use, why we use it, and how you can make choices about your data.",
        },
        "sections": [
            (
                "responsable",
                {"es": "Quién ofrece Petfy", "en": "Who offers Petfy"},
                {
                    "es": "<p>Petfy se ofrece bajo la marca <strong>Arvilo Labs</strong>. Su titular y responsable del tratamiento de datos es <strong>Brandon Stevens Aragón Mejía</strong>, establecido en Managua, Nicaragua.</p><p>Para consultas de privacidad, soporte o eliminación de cuenta, escribe a <a href='mailto:arvilolabs@gmail.com'>arvilolabs@gmail.com</a>. Esta página cubre Petfy para iPhone y iPad y este sitio público.</p>",
                    "en": "<p>Petfy is offered under the <strong>Arvilo Labs</strong> brand. Its owner and data controller is <strong>Brandon Stevens Aragón Mejía</strong>, established in Managua, Nicaragua.</p><p>For privacy, support, or account-deletion questions, email <a href='mailto:arvilolabs@gmail.com'>arvilolabs@gmail.com</a>. This page covers Petfy for iPhone and iPad and this public site.</p>",
                },
            ),
            (
                "datos",
                {"es": "Datos que utilizamos", "en": "Information we use"},
                {
                    "es": "<p>Según las funciones que elijas, podemos tratar:</p><ul><li><strong>Cuenta y perfil:</strong> correo, proveedor de acceso, nombre, foto, idioma, ciudad y preferencias.</li><li><strong>Mascotas y cuidados:</strong> perfiles, fotos, peso, alimentación, vacunas, medicamentos, citas, síntomas, notas y recordatorios.</li><li><strong>IA:</strong> tus mensajes, respuestas, mascota y contexto de cuidados que selecciones, eventos de consentimiento y reportes.</li><li><strong>Ubicación:</strong> coordenadas en primer plano cuando solicitas veterinarias cercanas; ciudad o país si los guardas en tu perfil.</li><li><strong>Dispositivo y compras:</strong> identificadores de instalación, tokens de notificación, versión de la app, producto, estado de Premium y referencias de transacción.</li><li><strong>Soporte y seguridad:</strong> mensajes de ayuda, eventos de sesión y errores filtrados para proteger y mantener el servicio.</li></ul><p>Petfy no solicita directamente números de tarjeta, documentos oficiales, contactos, grabaciones de micrófono ni ubicación continua en segundo plano en la versión actual. Apple gestiona el cobro de App Store.</p>",
                    "en": "<p>Depending on the features you choose, we may process:</p><ul><li><strong>Account and profile:</strong> email, sign-in provider, name, photo, language, city, and preferences.</li><li><strong>Pets and care:</strong> profiles, photos, weight, feeding, vaccines, medicines, appointments, symptoms, notes, and reminders.</li><li><strong>AI:</strong> your messages, responses, the pet and care context you select, consent events, and reports.</li><li><strong>Location:</strong> foreground coordinates when you request nearby vets; city or country if you save them to your profile.</li><li><strong>Device and purchases:</strong> installation identifiers, notification tokens, app version, product, Premium status, and transaction references.</li><li><strong>Support and security:</strong> help messages, session events, and filtered errors used to protect and maintain the service.</li></ul><p>The current Petfy app does not directly request payment-card numbers, government IDs, contacts, microphone recordings, or continuous background location. Apple handles App Store billing.</p>",
                },
            ),
            (
                "finalidades",
                {"es": "Para qué los usamos", "en": "Why we use it"},
                {
                    "es": "<p>Usamos los datos de cuenta, mascotas y cuidados para prestar las funciones que solicitas, sincronizar registros, enviar recordatorios, buscar veterinarias cuando lo pides y comprobar tu acceso Premium. La base de este tratamiento, cuando el RGPD sea aplicable, es la ejecución del servicio contratado contigo.</p><p>Petfy AI es opcional y trata el mensaje y contexto que selecciones después de tu consentimiento; puedes retirarlo. Tratamos mensajes de soporte para responder a tu solicitud y datos de diagnóstico y seguridad por nuestro interés legítimo en mantener un servicio seguro y estable. Conservamos los registros de compra que una obligación legal exija. No usamos estos datos para publicidad personalizada.</p>",
                    "en": "<p>We use account, pet, and care data to provide the features you request, sync records, send reminders, look up vets when asked, and check Premium access. Where the GDPR applies, the basis for this processing is performance of the service contract with you.</p><p>Petfy AI is optional and processes the message and context you select after your consent; you can withdraw it. We process support messages to answer your request and diagnostic and security data for our legitimate interest in keeping the service safe and reliable. We retain purchase records where a legal obligation requires it. We do not use this data for personalized advertising.</p>",
                },
            ),
            (
                "opciones",
                {"es": "Tus permisos y opciones", "en": "Your permissions and choices"},
                {
                    "es": "<p>La ubicación, el acceso a fotos y las notificaciones son opcionales. Puedes rechazarlos o revocarlos en los ajustes de iOS; las funciones que los necesitan dejarán de estar disponibles. Las búsquedas de veterinarias usan ubicación solo mientras realizas la búsqueda y Petfy no crea un historial de coordenadas.</p><p>Petfy AI requiere consentimiento dentro de la app. Puedes retirarlo y eliminar conversaciones guardadas desde los controles de IA.</p>",
                    "en": "<p>Location, photo access, and notifications are optional. You can decline or revoke them in iOS settings; features that need them will stop working. Vet searches use location only while you make the request, and Petfy does not create a coordinate history.</p><p>Petfy AI requires in-app consent. You can withdraw it and delete saved conversations through the AI controls.</p>",
                },
            ),
            (
                "proveedores",
                {"es": "Servicios que participan", "en": "Services involved"},
                {
                    "es": "<p>Para prestar las funciones usamos <strong>Supabase</strong> (cuentas, base de datos y archivos), <strong>OpenAI</strong> (respuestas de IA con el contexto elegido), <strong>Google Places/Maps</strong> (búsqueda de veterinarias), <strong>RevenueCat</strong> (estado de suscripción), <strong>Sentry</strong> (diagnósticos filtrados), <strong>Expo Push Service</strong> y <strong>Apple APNs</strong> (notificaciones). Apple interviene en el inicio de sesión con Apple, distribución y compras; Google también participa si eliges iniciar sesión con Google.</p><p>Supabase está alojado para Petfy en Estados Unidos (East US). Otros proveedores pueden tratar información fuera de tu país. Si resides en el EEE y deseas información sobre el país de destino y las garantías aplicables a una transferencia concreta, escríbenos al correo de privacidad. No vendemos tus datos personales a estos proveedores.</p>",
                    "en": "<p>To provide features, we use <strong>Supabase</strong> (accounts, database, and files), <strong>OpenAI</strong> (AI responses with selected context), <strong>Google Places/Maps</strong> (vet searches), <strong>RevenueCat</strong> (subscription state), <strong>Sentry</strong> (filtered diagnostics), <strong>Expo Push Service</strong>, and <strong>Apple APNs</strong> (notifications). Apple handles Sign in with Apple, distribution, and purchases; Google also participates if you choose Google sign-in.</p><p>Supabase for Petfy is hosted in the United States (East US). Other providers may process information outside your country. If you live in the EEA and want information about the destination country and safeguards applicable to a specific transfer, contact our privacy email. We do not sell your personal data to these providers.</p>",
                },
            ),
            (
                "conservacion",
                {"es": "Conservación y eliminación", "en": "Retention and deletion"},
                {
                    "es": "<p>Conservamos la cuenta y los registros de cuidado mientras exista tu cuenta o el registro correspondiente. Puedes borrar registros y conversaciones en Petfy y <a href='delete-account.html'>eliminar la cuenta</a>. Las coordenadas usadas para buscar veterinarias no se guardan como historial de ubicación.</p><p>Los mensajes de soporte se conservan hasta resolver el caso y el tiempo necesario para atender reclamaciones; los eventos de seguridad, consentimiento y diagnóstico, hasta completar su finalidad operativa o cumplir una obligación legal. Los registros de compra se conservan mientras sean necesarios para la suscripción, contabilidad o disputas. Las copias de seguridad se eliminan al completar su ciclo de rotación. Los proveedores pueden aplicar sus propios plazos; bajo la configuración estándar de OpenAI, los registros de monitorización de abuso pueden conservarse hasta 30 días. Puedes preguntar por un registro concreto en nuestro correo de privacidad.</p>",
                    "en": "<p>We keep account and care records while your account or the relevant record exists. You can delete records and conversations in Petfy and <a href='delete-account.html'>delete the account</a>. Coordinates used to find vets are not stored as a location history.</p><p>Support messages are kept until the case is resolved and for the time needed to address claims; security, consent, and diagnostic events until their operational purpose ends or a legal obligation applies. Purchase records remain as needed for the subscription, accounting, or disputes. Backups are removed through their rotation cycle. Providers may apply their own periods; under OpenAI's standard configuration, abuse-monitoring logs may be retained for up to 30 days. You can ask about a specific record at our privacy email.</p>",
                },
            ),
            (
                "derechos",
                {"es": "Tus derechos y seguridad", "en": "Your rights and security"},
                {
                    "es": "<p>Según tu país, puedes solicitar acceso, corrección, exportación, eliminación, limitación u oposición al tratamiento y retirar un consentimiento otorgado. Escríbenos desde el correo vinculado a tu cuenta a <a href='mailto:arvilolabs@gmail.com?subject=Petfy%20-%20Privacidad'>arvilolabs@gmail.com</a>. Podemos pedir verificación proporcional antes de actuar sobre datos de una cuenta.</p><p>Petfy usa acceso autenticado, reglas de propiedad sobre los datos y archivos privados. Filtra diagnósticos para reducir datos personales enviados a Sentry. Ningún servicio puede garantizar seguridad absoluta.</p>",
                    "en": "<p>Depending on your country, you may request access, correction, export, deletion, restriction, or objection, and withdraw consent you have given. Email us from the address linked to your account at <a href='mailto:arvilolabs@gmail.com?subject=Petfy%20-%20Privacy'>arvilolabs@gmail.com</a>. We may request proportionate verification before acting on account data.</p><p>Petfy uses authenticated access, ownership rules for data, and private files. It filters diagnostics to reduce personal information sent to Sentry. No service can guarantee absolute security.</p>",
                },
            ),
            (
                "menores",
                {"es": "Uso por menores", "en": "Use by minors"},
                {
                    "es": "<p>Petfy es un servicio de uso general y no fija una edad mínima adicional para todos los países. Si la ley de tu país exige autorización de un padre, madre o tutor para usar una función o tratar datos personales, esa autorización debe obtenerse antes de usarla. Si sabes que una cuenta de un menor trata datos sin la autorización exigida, escríbenos para que evaluemos su eliminación o restricción.</p>",
                    "en": "<p>Petfy is a general-audience service and does not set an additional worldwide minimum age. If your country's law requires parent or guardian authorization to use a feature or process personal data, that authorization must be obtained before use. If you know a minor's account processes data without required authorization, contact us so we can assess deletion or restriction.</p>",
                },
            ),
            (
                "sitio",
                {"es": "Este sitio web", "en": "This website"},
                {
                    "es": "<p>El selector de idioma guarda tu preferencia de español o inglés en el almacenamiento local del navegador. Este sitio no integra anuncios ni herramientas propias de seguimiento. GitHub Pages entrega las páginas y GitHub puede tratar datos técnicos de acceso bajo su <a href='https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement'>declaración de privacidad</a>.</p>",
                    "en": "<p>The language switcher saves your Spanish or English preference in your browser's local storage. This site does not include ads or our own tracking tools. GitHub Pages serves the pages, and GitHub may process technical access data under its <a href='https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement'>privacy statement</a>.</p>",
                },
            ),
            (
                "cambios",
                {"es": "Cambios y contacto", "en": "Changes and contact"},
                {
                    "es": "<p>Publicaremos una nueva fecha y versión cuando cambie esta política. Si el cambio necesita una comunicación o consentimiento adicional, lo gestionaremos antes de aplicarlo. Consultas: <a href='mailto:arvilolabs@gmail.com'>arvilolabs@gmail.com</a>.</p>",
                    "en": "<p>We will publish a new date and version when this policy changes. If a change requires additional notice or consent, we will handle it before it takes effect. Questions: <a href='mailto:arvilolabs@gmail.com'>arvilolabs@gmail.com</a>.</p>",
                },
            ),
        ],
    },
    "terms": {
        "file": "terms.html",
        "title": {"es": "Condiciones de uso", "en": "Terms of use"},
        "summary": {
            "es": "Reglas claras para usar Petfy, Premium y las funciones de ayuda para tu mascota.",
            "en": "Clear rules for using Petfy, Premium, and features that help with your pet.",
        },
        "sections": [
            ("servicio", {"es": "Petfy y tu cuenta", "en": "Petfy and your account"}, {"es": "<p>Petfy es operada por <strong>Brandon Stevens Aragón Mejía</strong> en Managua, Nicaragua, bajo la marca <strong>Arvilo Labs</strong>. Permite organizar mascotas, cuidados, recordatorios, fotos, reportes, veterinarias cercanas y funciones opcionales de IA. Debes mantener segura tu cuenta y proporcionar información que tengas derecho a utilizar.</p><p>Petfy no fija una edad mínima adicional a escala mundial. Si la ley de tu país exige autorización de un padre, madre o tutor, debes contar con ella antes de crear una cuenta o usar las funciones correspondientes.</p>", "en": "<p>Petfy is operated by <strong>Brandon Stevens Aragón Mejía</strong> in Managua, Nicaragua, under the <strong>Arvilo Labs</strong> brand. It helps organize pets, care records, reminders, photos, reports, nearby vets, and optional AI features. Keep your account secure and provide information you have the right to use.</p><p>Petfy does not set an additional worldwide minimum age. If your country's law requires parent or guardian authorization, you must have it before creating an account or using the relevant features.</p>"}),
            ("uso", {"es": "Uso responsable", "en": "Responsible use"}, {"es": "<p>No uses Petfy para infringir derechos de terceros, introducir contenido ilegal, eludir controles de acceso o compra, atacar el servicio, suplantar a otros ni perjudicar a personas o animales. Puedes eliminar tu cuenta desde la app.</p><p>Conservas los derechos sobre fotos y textos que aportas. Autorizas el tratamiento limitado necesario para almacenar, mostrar, sincronizar y proteger los contenidos de las funciones que solicitas.</p>", "en": "<p>Do not use Petfy to infringe others' rights, upload illegal material, bypass access or purchase controls, attack the service, impersonate others, or harm people or animals. You can delete your account in the app.</p><p>You retain rights to the photos and text you provide. You allow the limited processing needed to store, display, sync, and protect content for the features you request.</p>"}),
            ("premium", {"es": "Petfy Premium y compras", "en": "Petfy Premium and purchases"}, {"es": "<p>Petfy Premium ofrece opciones de suscripción semanal y anual con renovación automática mediante la App Store de Apple. El precio, moneda, impuestos, período y condiciones aplicables se muestran en la tienda antes de confirmar la compra. La suscripción se cobra a tu cuenta Apple y se renueva según sus reglas hasta que la canceles allí.</p><p>Puedes <a href='https://apps.apple.com/account/subscriptions'>administrar o cancelar suscripciones con Apple</a> y usar «Restaurar compras» en Petfy para recuperar acceso elegible. Desinstalar la app o eliminar tu cuenta Petfy <strong>no cancela</strong> una suscripción Apple. Las solicitudes de reembolso y los problemas de cobro se gestionan a través de Apple según sus reglas y la ley aplicable.</p>", "en": "<p>Petfy Premium offers weekly and annual auto-renewing subscriptions through Apple's App Store. The store shows the current price, currency, taxes, period, and applicable terms before you confirm. Billing goes to your Apple account and renews under its rules until you cancel there.</p><p>You can <a href='https://apps.apple.com/account/subscriptions'>manage or cancel subscriptions with Apple</a> and use “Restore purchases” in Petfy to recover eligible access. Uninstalling the app or deleting your Petfy account <strong>does not cancel</strong> an Apple subscription. Refund requests and billing issues go through Apple under its rules and applicable law.</p>"}),
            ("cuidados", {"es": "Cuidados, IA y terceros", "en": "Care, AI, and third parties"}, {"es": "<p>Petfy es una herramienta de organización e información. No diagnostica, receta ni sustituye a un veterinario. Verifica medicamentos, dosis, síntomas y decisiones clínicas con un profesional; busca atención urgente cuando sea necesario.</p><p>Petfy AI necesita consentimiento y puede responder de forma incorrecta o incompleta. Los resultados de veterinarias provienen de servicios externos y pueden cambiar; comprueba horarios, disponibilidad y ubicación con la clínica.</p>", "en": "<p>Petfy is an organization and information tool. It does not diagnose, prescribe, or replace a veterinarian. Check medicine, doses, symptoms, and clinical decisions with a professional; seek urgent care when needed.</p><p>Petfy AI requires consent and may give incomplete or wrong answers. Vet results come from external services and can change; confirm hours, availability, and location with the clinic.</p>"}),
            ("cambios", {"es": "Cambios, derechos y ayuda", "en": "Changes, rights, and help"}, {"es": "<p>Podemos modificar funciones por seguridad, requisitos de tienda, razones técnicas o mejoras del servicio. Los cambios materiales de estas condiciones tendrán una nueva versión y fecha y se comunicarán cuando lo exija la ley.</p><p>Estas condiciones se interpretan conforme a la ley de Nicaragua, sin limitar los derechos irrenunciables del consumidor en su lugar de residencia. Ninguna disposición excluye responsabilidades que la ley no permita excluir. Antes de iniciar una reclamación, puedes escribir a <a href='mailto:arvilolabs@gmail.com'>arvilolabs@gmail.com</a> para intentar resolverla; conservas el derecho de acudir a la autoridad o tribunal competente.</p>", "en": "<p>We may change features for security, store requirements, technical reasons, or service improvements. Material changes to these terms will carry a new version and date and will be communicated when the law requires it.</p><p>These terms are interpreted under Nicaraguan law without limiting mandatory consumer rights where you live. No provision excludes liability that law does not allow us to exclude. Before making a claim, you may email <a href='mailto:arvilolabs@gmail.com'>arvilolabs@gmail.com</a> to seek a resolution; you retain the right to contact a competent authority or court.</p>"}),
        ],
    },
    "delete-account": {
        "file": "delete-account.html",
        "title": {"es": "Eliminar tu cuenta", "en": "Delete your account"},
        "summary": {"es": "Puedes iniciar el borrado desde Petfy o escribirnos si ya no puedes entrar.", "en": "You can start deletion in Petfy or email us if you can no longer sign in."},
        "sections": [
            ("app", {"es": "Desde la app", "en": "In the app"}, {"es": "<ol><li>Abre Petfy e inicia sesión en la cuenta correcta.</li><li>Entra en <strong>Más / Configuración</strong> y abre <strong>Seguridad</strong>.</li><li>Toca <strong>Eliminar cuenta y datos</strong>.</li><li>Lee la confirmación. Si Petfy lo solicita, vuelve a autenticarte con correo, Apple o Google y confirma.</li></ol><p>Esta opción elimina la cuenta completa, no solo la desactiva.</p>", "en": "<ol><li>Open Petfy and sign in to the account you want to delete.</li><li>Go to <strong>More / Settings</strong> and open <strong>Security</strong>.</li><li>Tap <strong>Delete account and data</strong>.</li><li>Read the confirmation. If Petfy asks, authenticate again with email, Apple, or Google and confirm.</li></ol><p>This option deletes the whole account, not just deactivates it.</p>"}),
            ("sin-acceso", {"es": "Si no puedes entrar", "en": "If you cannot sign in"}, {"es": "<p>Envía un correo desde la dirección asociada a tu cuenta a <a href='mailto:arvilolabs@gmail.com?subject=Eliminar%20cuenta%20Petfy'>arvilolabs@gmail.com</a> con el asunto «Eliminar cuenta Petfy». Te indicaremos un método de verificación antes de actuar y confirmaremos el resultado. En el primer mensaje no adjuntes contraseña, datos de tarjeta ni documentos de identidad. Atenderemos la solicitud sin demora indebida y según los plazos exigidos por la ley aplicable.</p>", "en": "<p>Email us from the address associated with your account at <a href='mailto:arvilolabs@gmail.com?subject=Delete%20Petfy%20account'>arvilolabs@gmail.com</a> with the subject “Delete Petfy account.” We will provide a verification method before acting and confirm the outcome. Do not attach a password, payment-card details, or government ID to the first message. We will handle the request without undue delay and within periods required by applicable law.</p>"}),
            ("alcance", {"es": "Qué se elimina", "en": "What is deleted"}, {"es": "<p>El proceso elimina tu usuario de Petfy, perfil, archivos privados vinculados y registros propios de mascotas, cuidados, recordatorios, favoritos, dispositivos, conversaciones de IA y proyecciones de acceso Premium. Algunos registros de transacción, seguridad, consentimiento o disputas pueden conservarse cuando una obligación legal lo exija o mientras sean necesarios para resolver el caso, según los criterios de la <a href='privacy.html'>política de privacidad</a>. Apple conserva por separado el historial requerido por sus propias obligaciones.</p>", "en": "<p>The process deletes your Petfy user, profile, linked private files, and account-owned pet, care, reminder, favorite, device, AI-conversation, and Premium-access records. Some transaction, security, consent, or dispute records may be retained where legally required or while needed to resolve the matter, under the criteria in the <a href='privacy.html'>privacy policy</a>. Apple separately retains history required under its own obligations.</p>"}),
            ("suscripcion", {"es": "Antes de borrar: cancela Premium", "en": "Before deletion: cancel Premium"}, {"es": "<p><strong>Borrar la cuenta o desinstalar Petfy no detiene el cobro de una suscripción Apple.</strong> Si tienes Premium con renovación automática, cancélalo antes desde <a href='https://apps.apple.com/account/subscriptions'>Suscripciones de Apple</a> o en iPhone/iPad: Ajustes → tu nombre → Suscripciones → Petfy. Apple gestiona las renovaciones y reembolsos.</p>", "en": "<p><strong>Deleting the account or uninstalling Petfy does not stop billing for an Apple subscription.</strong> If you have auto-renewing Premium, cancel it first through <a href='https://apps.apple.com/account/subscriptions'>Apple Subscriptions</a> or on iPhone/iPad: Settings → your name → Subscriptions → Petfy. Apple handles renewals and refunds.</p>"}),
        ],
    },
    "ai-notice": {
        "file": "ai-notice.html",
        "title": {"es": "Cómo funciona Petfy AI", "en": "How Petfy AI works"},
        "summary": {"es": "Una ayuda para organizar información, con consentimiento y límites claros.", "en": "A way to organize information, with clear consent and limitations."},
        "sections": [
            ("envio", {"es": "Qué se envía", "en": "What is sent"}, {"es": "<p>Cuando aceptas usar Petfy AI y haces una consulta, se envía tu mensaje y el contexto de la mascota y sus cuidados que selecciones a la función segura de Petfy y al proveedor OpenAI para producir una respuesta. La conversación y la respuesta pueden guardarse en tu cuenta para que las consultes después.</p><p>No compartas contraseñas, datos de tarjeta o documentos oficiales en tus preguntas.</p>", "en": "<p>When you consent to Petfy AI and ask a question, your message and the pet and care context you select are sent to Petfy's secured function and to OpenAI for a response. The conversation and response may be stored in your account so you can revisit them.</p><p>Do not include passwords, card details, or government IDs in prompts.</p>"}),
            ("control", {"es": "Tú tienes el control", "en": "You stay in control"}, {"es": "<p>La IA es opcional y exige consentimiento en la app. Puedes retirar ese consentimiento, borrar una conversación o borrar las conversaciones guardadas. Los registros de seguridad y prueba de consentimiento se conservan solo conforme a las finalidades y criterios de la <a href='privacy.html'>política de privacidad</a>.</p>", "en": "<p>AI is optional and requires in-app consent. You can withdraw it, delete one conversation, or delete saved conversations. Security and consent-evidence records are kept only under the purposes and criteria in the <a href='privacy.html'>privacy policy</a>.</p>"}),
            ("limites", {"es": "No sustituye a un veterinario", "en": "It does not replace a veterinarian"}, {"es": "<p>La IA puede equivocarse, omitir información o ofrecer una respuesta inadecuada. No la uses para diagnóstico, dosis, urgencias o tratamiento. Si tu mascota presenta dificultad respiratoria, convulsiones, intoxicación, sangrado u otro síntoma grave, busca atención veterinaria inmediata.</p>", "en": "<p>AI may be wrong, omit information, or give an unsuitable answer. Do not use it for diagnosis, doses, emergencies, or treatment. If your pet has breathing difficulty, seizures, poisoning, bleeding, or another serious symptom, seek veterinary care immediately.</p>"}),
        ],
    },
    "dmca": {
        "file": "dmca.html",
        "title": {"es": "Derechos de autor", "en": "Copyright"},
        "summary": {"es": "Cómo avisarnos si crees que un contenido de Petfy infringe tus derechos.", "en": "How to tell us if you believe Petfy content infringes your rights."},
        "sections": [
            ("reporte", {"es": "Enviar un aviso", "en": "Send a notice"}, {"es": "<p>Escribe a <a href='mailto:arvilolabs@gmail.com?subject=Petfy%20-%20Derechos%20de%20autor'>arvilolabs@gmail.com</a> con tu nombre y contacto, la obra protegida, el contenido concreto y dónde aparece, y una explicación de por qué consideras que no está autorizado. No envíes documentos de identidad en el primer correo.</p>", "en": "<p>Email <a href='mailto:arvilolabs@gmail.com?subject=Petfy%20-%20Copyright'>arvilolabs@gmail.com</a> with your name and contact details, the protected work, the specific content and where it appears, and why you believe it is unauthorized. Do not send government IDs in the first email.</p>"}),
            ("respuesta", {"es": "Si se retiró por error", "en": "If removal was a mistake"}, {"es": "<p>Puedes responder al mismo correo con el contexto y la prueba que consideres pertinente. Evaluaremos el aviso y podremos pedir información adicional antes de decidir.</p>", "en": "<p>You can reply to the same address with relevant context and evidence. We will assess the notice and may ask for more information before deciding.</p>"}),
        ],
    },
}
